#!/usr/bin/env nu
#
# Install a Windows game launcher into its own umu-launcher Wine prefix, and
# generate launch/exec/desktop/uninstall helpers for it.
#
# umu-launcher is the Proton backend Lutris/Heroic use: it creates and runs a
# detached Wine prefix without Steam, and a GAMEID from the umu database pulls
# in that game's protonfixes (fonts, env quirks, save location, ...). This
# installer is fully generic -- it knows no game names. Every per-game detail
# lives under ~/Games/<name>/:
#
#   prefix      the Wine prefix (WINEPREFIX)
#   prelaunch   optional executable, run before every launch
#   conf        optional shell file overriding the generated defaults
#   run         generated launcher
#   exec        generated helper: run any exe/wine tool in the prefix
#   <name>.desktop  generated desktop entry
#   uninstall   generated: drop the desktop entry and (with confirmation) this dir
#
# ~/Games/global.conf, if present, is sourced by every run script before the
# game's own conf; both may set ENABLE_GAMEMODE, ENABLE_GAMESCOPE,
# GAMESCOPE_ARGS, ENABLE_LOG, PROTONPATH, GAMEID, LAUNCHER, ...
#
# PROTONPATH is resolved from $PROTONPATH, then $UMU_PROTONPATH (exported by
# modules/nixos/desktop/gaming.nix from pkgs.dwproton-bin), then the newest
# dwproton in /nix/store, then Steam's per-user compatibilitytools.d.
#
#   nu .agents/skills/nix-config-umu-game/scripts/umu-install.nu wuthering-waves \
#     ~/Downloads/WutheringWaves_setup_3.5.0.exe \
#     "drive_c/Program Files/Wuthering Waves/launcher.exe" \
#     umu-3513350
#
# Extra arguments after [gameid] are passed to the installer, e.g. "/S" or
# "/quiet" for a silent install.

def games-dir [] {
  $env.UMU_GAMES_DIR? | default ($nu.home-dir | path join "Games")
}

# Newest Nix-provided DW-Proton, if any.
def dwproton-store [] {
  let hits = (glob "/nix/store/*-dwproton-bin-*-steamcompattool")
  if ($hits | is-empty) { null } else { $hits | last }
}

# First candidate that actually contains a proton script.
def resolve-protonpath [] {
  let explicit = ($env.PROTONPATH? | default "")
  if (not ($explicit | is-empty)) and (($explicit | path join "proton") | path exists) {
    return $explicit
  }
  let umu = ($env.UMU_PROTONPATH? | default "")
  if (not ($umu | is-empty)) and (($umu | path join "proton") | path exists) {
    return $umu
  }
  let store = (dwproton-store)
  if $store != null {
    return $store
  }
  let steam = ($nu.home-dir | path join ".local/share/Steam/compatibilitytools.d/dwproton")
  if (($steam | path join "proton") | path exists) {
    return $steam
  }
  null
}

# "wuthering-waves" -> "Wuthering Waves"
def display-name [name: string] {
  $name | split row "-" | each { |w| $w | str capitalize } | str join " "
}

def usage [] {
  print "Usage: .agents/skills/nix-config-umu-game/scripts/umu-install.nu <name> <setup.exe> <launcher> [gameid] [setup-args...]"
  print ""
  print "  <name>       directory under ~/Games (e.g. wuthering-waves)"
  print "  <setup.exe>  installer to run through umu (a host path)"
  print "  <launcher>   launcher to run later, relative to the prefix"
  print "  [gameid]     umu database id for protonfixes (default umu-default)"
  print "  [setup-args] extra args for setup.exe, e.g. /S or /quiet"
  print ""
  print "Writes ~/Games/<name>/{run,exec,<name>.desktop,uninstall}. A per-game"
  print "fix goes in ~/Games/<name>/prelaunch; overrides go in ~/Games/<name>/conf"
  print "or ~/Games/global.conf. PROTONPATH comes from $PROTONPATH,"
  print "$UMU_PROTONPATH, or the newest dwproton in /nix/store."
}

def write-run [name: string, launcher: string] {
  let dir = ((games-dir) | path join $name)
  let prelaunch = ($dir | path join "prelaunch")
  let run = ($dir | path join "run")
  let runner = ($dir | path join "exec")
  let content = ([
    '#!/usr/bin/env bash'
    ('# Generated by the nix-config-umu-game skill -- re-run its script to regenerate.')
    'set -euo pipefail'
    'HERE="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"'
    '# Defaults; ~/Games/global.conf and this game conf/ override them.'
    ('WINEPREFIX="' + $env.WINEPREFIX + '"')
    ('PROTONPATH="${PROTONPATH:-${UMU_PROTONPATH:-' + $env.PROTONPATH + '}}"')
    ('GAMEID="' + $env.GAMEID + '"')
    ('LAUNCHER="' + $launcher + '"')
    'ENABLE_GAMEMODE=0'
    'ENABLE_GAMESCOPE=0'
    'GAMESCOPE_ARGS="-f"'
    'ENABLE_LOG=0'
    'if [ -f "$HERE/../global.conf" ]; then . "$HERE/../global.conf"; fi'
    'if [ -f "$HERE/conf" ]; then . "$HERE/conf"; fi'
    'export WINEPREFIX PROTONPATH GAMEID'
    'export VKD3D_SHADER_CACHE_PATH="$HERE/shader-cache"'
    'mkdir -p "$VKD3D_SHADER_CACHE_PATH"'
    'PRE=""'
    'if [ "$ENABLE_GAMEMODE" = "1" ] && command -v gamemoderun >/dev/null 2>&1; then PRE="gamemoderun"; fi'
    'if [ "$ENABLE_GAMESCOPE" = "1" ] && command -v gamescope >/dev/null 2>&1; then PRE="$PRE gamescope $GAMESCOPE_ARGS --"; fi'
    ('if [ -x "' + $prelaunch + '" ]; then "' + $prelaunch + '"; fi')
    'if [ "$ENABLE_LOG" = "1" ]; then'
    '  set -o pipefail'
    '  $PRE umu-run "$WINEPREFIX/$LAUNCHER" "$@" 2>&1 | tee "$HERE/last-run.log"'
    'else'
    '  exec $PRE umu-run "$WINEPREFIX/$LAUNCHER" "$@"'
    'fi'
    ''
  ] | str join (char nl))
  let execContent = ([
    '#!/usr/bin/env bash'
    ('# Generated by the nix-config-umu-game skill -- run a tool in this prefix.')
    '#   exec <exe-or-tool> [args...]    e.g. exec winecfg / exec explorer'
    'set -euo pipefail'
    ('export WINEPREFIX="' + $env.WINEPREFIX + '"')
    ('export PROTONPATH="${PROTONPATH:-${UMU_PROTONPATH:-' + $env.PROTONPATH + '}}"')
    ('export GAMEID="' + $env.GAMEID + '"')
    '# Bare wine tools are not executables on disk; run them through Proton wine.'
    'case "${1:-}" in'
    '  winecfg|wineboot|explorer|regedit|control|uninstaller|taskmgr)'
    '    exec umu-run "$PROTONPATH/files/bin/wine" "$@" ;;'
    '  *)'
    '    exec umu-run "$@" ;;'
    'esac'
    ''
  ] | str join (char nl))
  mkdir $dir
  $content | save --force $run
  ^chmod +x $run
  $execContent | save --force $runner
  ^chmod +x $runner
}

def write-integration [name: string] {
  let home = $nu.home-dir
  let dir = ((games-dir) | path join $name)
  let apps = ($home | path join ".local/share/applications")
  let desktop = ([
    '[Desktop Entry]'
    'Type=Application'
    ('Name=' + (display-name $name))
    'Comment=Windows game launcher installed via umu'
    ('Exec=' + ($dir | path join "run"))
    ('Path=' + $dir)
    'Terminal=false'
    'Categories=Game;'
    'StartupNotify=false'
    ''
  ] | str join (char nl))
  $desktop | save --force ($dir | path join $"($name).desktop")
  if not ($apps | path exists) {
    mkdir $apps
  }
  $desktop | save --force ($apps | path join $"($name).desktop")

  let uninstall = ([
    '#!/usr/bin/env bash'
    ('# Generated by the nix-config-umu-game skill: remove ' + $name + '.')
    'set -euo pipefail'
    'HERE="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"'
    ('rm -f "' + ($apps | path join $"($name).desktop") + '"')
    'echo "desktop entry removed"'
    'printf "Delete %s and all its files? [y/N] " "$HERE"'
    'read -r ans'
    'if [ "$ans" = y ] || [ "$ans" = Y ]; then'
    '  cd /'
    '  rm -rf "$HERE"'
    '  echo "removed $HERE"'
    'else'
    '  echo "kept $HERE"'
    'fi'
    ''
  ] | str join (char nl))
  $uninstall | save --force ($dir | path join "uninstall")
  ^chmod +x ($dir | path join "uninstall")
}

def main [...args: string] {
  if ($args | length) < 3 {
    usage
    exit 1
  }
  let name = ($args | get 0)
  let setup = ($args | get 1)
  let launcher = ($args | get 2)
  let gameid = (if ($args | length) >= 4 { $args | get 3 } else { "umu-default" })
  let setupArgs = (if ($args | length) >= 5 { $args | skip 4 } else { [] })

  let protonpath = (resolve-protonpath)
  if $protonpath == null {
    print --stderr "error: no Proton found. Set PROTONPATH or UMU_PROTONPATH, or rebuild NixOS so modules/nixos/desktop/gaming.nix exports UMU_PROTONPATH."
    exit 1
  }
  $env.PROTONPATH = $protonpath

  let dir = ((games-dir) | path join $name)
  $env.WINEPREFIX = ($dir | path join "prefix")
  $env.GAMEID = $gameid

  print $"installing '($name)' into ($env.WINEPREFIX)"
  print $"  PROTONPATH = ($env.PROTONPATH)"
  print $"  GAMEID     = ($env.GAMEID)"
  print "run the installer, then exit it (do not start the game)."

  let inst = (^umu-run $setup ...$setupArgs | complete)
  if $inst.exit_code != 0 {
    print --stderr $"installer exited ($inst.exit_code); writing the launchers anyway"
  }

  let prelaunch = ($dir | path join "prelaunch")
  if ($prelaunch | path exists) {
    print $"running prelaunch: ($prelaunch)"
    run-external $prelaunch
  }

  write-run $name $launcher
  write-integration $name
  print $"done. launch with: ($dir)/run"
}
