{
 "title": "UPS / NUT Exporter",
 "description": "Network UPS Tools metrics collected by nut_exporter. Adapted from https://github.com/DRuggeri/nut_exporter/blob/master/dashboard/dashboard.json",
 "tags": [
  "homelab",
  "nut",
  "ups"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(network_ups_tools_device_info, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(network_ups_tools_device_info{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$job / $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ups" },
  {
   "title": "UPS Status",
   "type": "stat",
   "description": " * OL - On line (mains is present)\n * OB - On battery (mains is not present)\n * LB - Low battery\n * HB - High battery\n * RB - The battery needs to be replaced\n * CHRG - The battery is charging\n * DISCHRG - The battery is discharging (inverter is providing load power)\n * BYPASS - UPS bypass circuit is active -- no battery protection is available\n * CAL - UPS is currently performing runtime calibration (on battery)\n * OFF - UPS is offline and is not supplying power to the load\n * OVER - UPS is overloaded\n * TRIM - UPS is trimming incoming voltage (called \"buck\" in some hardware)\n * BOOST - UPS is boosting incoming voltage\n * FSD and SD - Forced Shutdown",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{instance=~\"$instance\",job=~\"$job\"} == 1",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Input Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_input_frequency{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_output_voltage{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Output Voltage History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_output_voltage{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Output Voltage History"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "UPS Temperature",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_temperature{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Line Volts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Input Voltage History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Input voltage"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Battery voltage"
    }
   ]
  },
  {
   "title": "Battery Voltage History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Battery voltage"
    }
   ]
  }
 ]
}