#!/usr/bin/env bash
# Generated by the nix-config-umu-game skill -- run a tool in this prefix.
#   exec <exe-or-tool> [args...]    e.g. exec winecfg / exec explorer
set -euo pipefail
export WINEPREFIX=@WINEPREFIX@
DEFAULT_PROTONPATH=@PROTONPATH@
export PROTONPATH="${PROTONPATH:-${UMU_PROTONPATH:-$DEFAULT_PROTONPATH}}"
export GAMEID=@GAMEID@
# Bare wine tools are not executables on disk; run them through Proton wine.
case "${1:-}" in
  winecfg|wineboot|explorer|regedit|control|uninstaller|taskmgr)
    exec umu-run "$PROTONPATH/files/bin/wine" "$@" ;;
  *)
    exec umu-run "$@" ;;
esac
