#!/usr/bin/env bash
# Generated by the nix-config-umu-game skill.
set -euo pipefail
HERE="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
rm -f @DESKTOP_FILE@
echo "desktop entry removed"
printf "Delete %s and all its files? [y/N] " "$HERE"
read -r ans
if [ "$ans" = y ] || [ "$ans" = Y ]; then
  cd /
  rm -rf "$HERE"
  echo "removed $HERE"
else
  echo "kept $HERE"
fi
