#!/usr/bin/env bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Arc-Dark'
ICONS='Zafiro-Blue'
FONT='Noto Sans 9'
CURSOR='Qogirr'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
