#!/usr/bin/env nu
#
# Install a Windows game launcher into its own umu-launcher Wine prefix, and
# generate launch/exec scripts for it.
#
# umu-launcher is the Proton backend Lutris/Heroic use: it creates and runs a
# detached Wine prefix without Steam, and a GAMEID from the umu database pulls
# in that game's protonfixes (fonts, env quirks, save location, ...). This
# installer is fully generic -- it knows no game names. Every per-game detail
# lives under ~/Games/<name>/:
#
#   prefix      the Wine prefix (WINEPREFIX)
#   prelaunch   optional executable, run before every launch
#   conf        optional shell file overriding the generated defaults
#   run         generated launcher
#   exec        generated helper: run any exe/tool in the prefix
#
# ~/Games/global.conf, if present, is sourced by every run script before the
# game's own conf; both may set ENABLE_GAMEMODE, ENABLE_GAMESCOPE,
# GAMESCOPE_ARGS, ENABLE_LOG, PROTONPATH, GAMEID, LAUNCHER, ...
#
#   just umu-install wuthering-waves \
#     ~/Downloads/WutheringWaves_setup_3.5.0.exe \
#     "drive_c/Program Files/Wuthering Waves/launcher.exe" \
#     umu-3513350

# Defaults to the DW-Proton compatibility tool installed by programs.steam.
$env.PROTONPATH = ($env.PROTONPATH? | default ($nu.home-dir | path join ".local/share/Steam/compatibilitytools.d" "dwproton"))

def games-dir [] {
  $env.UMU_GAMES_DIR? | default ($nu.home-dir | path join "Games")
}

def usage [] {
  print "Usage: just umu-install <name> <setup.exe> <launcher> [gameid]"
  print ""
  print "  <name>      directory under ~/Games (e.g. wuthering-waves)"
  print "  <setup.exe> installer to run through umu (a host path)"
  print "  <launcher>  launcher to run later, relative to the prefix"
  print "  [gameid]    umu database id for protonfixes (default umu-default)"
  print ""
  print "Writes ~/Games/<name>/run and ~/Games/<name>/exec. A per-game fix"
  print "goes in ~/Games/<name>/prelaunch; overrides go in ~/Games/<name>/conf"
  print "or ~/Games/global.conf."
}

def write-run [name: string, launcher: string] {
  let dir = ((games-dir) | path join $name)
  let prelaunch = ($dir | path join "prelaunch")
  let run = ($dir | path join "run")
  let runner = ($dir | path join "exec")
  let content = ([
    '#!/usr/bin/env bash'
    ('# Generated by just umu-install ' + $name + ' -- re-run that to regenerate.')
    'set -euo pipefail'
    'HERE="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"'
    '# Defaults; ~/Games/global.conf and this game conf/ override them.'
    ('WINEPREFIX="' + $env.WINEPREFIX + '"')
    ('PROTONPATH="' + $env.PROTONPATH + '"')
    ('GAMEID="' + $env.GAMEID + '"')
    ('LAUNCHER="' + $launcher + '"')
    'ENABLE_GAMEMODE=0'
    'ENABLE_GAMESCOPE=0'
    'GAMESCOPE_ARGS="-f"'
    'ENABLE_LOG=0'
    'if [ -f "$HERE/../global.conf" ]; then . "$HERE/../global.conf"; fi'
    'if [ -f "$HERE/conf" ]; then . "$HERE/conf"; fi'
    'export WINEPREFIX PROTONPATH GAMEID'
    'export VKD3D_SHADER_CACHE_PATH="$HERE/shader-cache"'
    'mkdir -p "$VKD3D_SHADER_CACHE_PATH"'
    'PRE=""'
    'if [ "$ENABLE_GAMEMODE" = "1" ] && command -v gamemoderun >/dev/null 2>&1; then PRE="gamemoderun"; fi'
    'if [ "$ENABLE_GAMESCOPE" = "1" ] && command -v gamescope >/dev/null 2>&1; then PRE="$PRE gamescope $GAMESCOPE_ARGS --"; fi'
    ('if [ -x "' + $prelaunch + '" ]; then "' + $prelaunch + '"; fi')
    'if [ "$ENABLE_LOG" = "1" ]; then'
    '  set -o pipefail'
    '  $PRE umu-run "$WINEPREFIX/$LAUNCHER" "$@" 2>&1 | tee "$HERE/last-run.log"'
    'else'
    '  exec $PRE umu-run "$WINEPREFIX/$LAUNCHER" "$@"'
    'fi'
    ''
  ] | str join (char nl))
  let execContent = ([
    '#!/usr/bin/env bash'
    ('# Generated by just umu-install ' + $name + ' -- run a tool in this prefix.')
    '#   exec <exe-or-tool> [args...]    e.g. exec winecfg / exec explorer'
    'set -euo pipefail'
    ('export WINEPREFIX="' + $env.WINEPREFIX + '"')
    ('export PROTONPATH="' + $env.PROTONPATH + '"')
    ('export GAMEID="' + $env.GAMEID + '"')
    'exec umu-run "$@"'
    ''
  ] | str join (char nl))
  mkdir $dir
  $content | save --force $run
  ^chmod +x $run
  $execContent | save --force $runner
  ^chmod +x $runner
}

def main [...args: string] {
  if ($args | length) < 3 {
    usage
    exit 1
  }
  let name = ($args | get 0)
  let setup = ($args | get 1)
  let launcher = ($args | get 2)
  let gameid = (if ($args | length) >= 4 { $args | get 3 } else { "umu-default" })

  let dir = ((games-dir) | path join $name)
  $env.WINEPREFIX = ($dir | path join "prefix")
  $env.GAMEID = $gameid

  print $"installing '($name)' into ($env.WINEPREFIX)"
  print $"  PROTONPATH = ($env.PROTONPATH)"
  print $"  GAMEID     = ($env.GAMEID)"
  print "run the installer, then exit it (do not start the game)."

  ^umu-run $setup

  let prelaunch = ($dir | path join "prelaunch")
  if ($prelaunch | path exists) {
    print $"running prelaunch: ($prelaunch)"
    run-external $prelaunch
  }

  write-run $name $launcher
  print $"done. launch with: ($dir)/run"
}
