#!/usr/bin/env nu
#
# Install a Windows game launcher into its own umu-launcher Wine prefix, and
# generate a launch script for it.
#
# umu-launcher is the Proton backend Lutris/Heroic use: it creates and runs a
# detached Wine prefix without Steam, and a GAMEID from the umu database pulls
# in that game's protonfixes (fonts, env quirks, ...). This installer is fully
# generic -- it knows no game names. Every per-game detail lives under
# ~/Games/<name>/, including an optional executable "prelaunch" that runs before
# each launch (see the nix-config-umu-game skill).
#
#   just umu-install wuthering-waves \
#     ~/Downloads/WutheringWaves_setup_3.5.0.exe \
#     "drive_c/Program Files/Wuthering Waves/launcher.exe" \
#     umu-3513350
#
# Layout (wuthering-waves example):
#   ~/Games/wuthering-waves/prefix     the Wine prefix (WINEPREFIX)
#   ~/Games/wuthering-waves/prelaunch  optional, run before every launch
#   ~/Games/wuthering-waves/run        generated launch script

# Defaults to the DW-Proton compatibility tool installed by programs.steam.
$env.PROTONPATH = ($env.PROTONPATH? | default ($nu.home-dir | path join ".local/share/Steam/compatibilitytools.d" "dwproton"))

def games-dir [] {
  $env.UMU_GAMES_DIR? | default ($nu.home-dir | path join "Games")
}

def usage [] {
  print "Usage: just umu-install <name> <setup.exe> <launcher> [gameid]"
  print ""
  print "  <name>      directory under ~/Games (e.g. wuthering-waves)"
  print "  <setup.exe> installer to run through umu (a host path)"
  print "  <launcher>  launcher to run later, relative to the prefix"
  print "  [gameid]    umu database id for protonfixes (default umu-default)"
  print ""
  print "A per-game fix goes in ~/Games/<name>/prelaunch (executable); it runs"
  print "after the install and before every launch."
}

def write-run [name: string, launcher: string] {
  let dir = ((games-dir) | path join $name)
  let run = ($dir | path join "run")
  let prelaunch = ($dir | path join "prelaunch")
  let content = ([
    '#!/usr/bin/env bash'
    ('# Generated by just umu-install ' + $name + ' -- re-run that to regenerate.')
    'set -euo pipefail'
    ('export WINEPREFIX="' + $env.WINEPREFIX + '"')
    ('export PROTONPATH="' + $env.PROTONPATH + '"')
    ('export GAMEID="' + $env.GAMEID + '"')
    ('if [ -x "' + $prelaunch + '" ]; then "' + $prelaunch + '"; fi')
    ('exec umu-run "' + ($env.WINEPREFIX | path join $launcher) + '" "$@"')
    ''
  ] | str join (char nl))
  mkdir $dir
  $content | save --force $run
  ^chmod +x $run
}

def main [...args: string] {
  if ($args | length) < 3 {
    usage
    exit 1
  }
  let name = ($args | get 0)
  let setup = ($args | get 1)
  let launcher = ($args | get 2)
  let gameid = (if ($args | length) >= 4 { $args | get 3 } else { "umu-default" })

  let dir = ((games-dir) | path join $name)
  $env.WINEPREFIX = ($dir | path join "prefix")
  $env.GAMEID = $gameid

  print $"installing '($name)' into ($env.WINEPREFIX)"
  print $"  PROTONPATH = ($env.PROTONPATH)"
  print $"  GAMEID     = ($env.GAMEID)"
  print "run the installer, then exit it (do not start the game)."

  ^umu-run $setup

  let prelaunch = ($dir | path join "prelaunch")
  if ($prelaunch | path exists) {
    print $"running prelaunch: ($prelaunch)"
    run-external $prelaunch
  }

  write-run $name $launcher

  print $"done. launch with: ($dir)/run"
}
