{
 "title": "Kubernetes / Storage / Persistent Volumes",
 "description": "Monitors all persistent volumes that exists within a Kubernetes cluster. Prometheus is used as datasource. ",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   { "name": "warning_threshold", "label": "PVC % Used Warning Threshold", "query": "80" }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PVCs Full in 2 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"}[1d], 2 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 5 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"}[1d], 5 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 1 Week - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Above Warning Threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"} ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"} )) >= (${warning_threshold} / 100)) or vector (0)"
    }
   ]
  },
  {
   "title": "PVCs in Pending State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\",phase=\"Pending\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "PVCs in Lost State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\",phase=\"Lost\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "Usage statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Persistent Volume Claim",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(sum by (persistentvolumeclaim, namespace, storageclass, volumename) (kube_persistentvolumeclaim_info{cluster=\"$cluster\", namespace=~\"$namespace\"}), \"pvc_key\", \"/\", \"namespace\", \"persistentvolumeclaim\")"
    },
    {
     "expr": "sum by (pvc_key) (label_join(sum by (persistentvolumeclaim, namespace) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"} / 1024 / 1024 / 1024), \"pvc_key\", \"/\", \"namespace\", \"persistentvolumeclaim\"))"
    },
    {
     "expr": "sum by (pvc_key) (label_join(sum by (persistentvolumeclaim, namespace) (kubelet_volume_stats_used_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"} / 1024 / 1024 / 1024), \"pvc_key\", \"/\", \"namespace\", \"persistentvolumeclaim\"))"
    },
    {
     "expr": "sum by (pvc_key) (label_join(sum by (persistentvolumeclaim, namespace) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"} / 1024 / 1024 / 1024), \"pvc_key\", \"/\", \"namespace\", \"persistentvolumeclaim\"))"
    },
    {
     "expr": "sum by (pvc_key) (label_join(sum by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", phase=~\"(Pending|Lost)\"}) + sum by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", phase=\"Lost\"}), \"pvc_key\", \"/\", \"namespace\", \"persistentvolumeclaim\"))"
    },
    {
     "expr": "sum by (pvc_key) (label_join(sum by (persistentvolumeclaim, namespace) (kubelet_volume_stats_used_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"} * 100), \"pvc_key\", \"/\", \"namespace\", \"persistentvolumeclaim\"))"
    }
   ]
  },
  {
   "title": "Storage Class",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "kube_storageclass_info{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Graphical usage data ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Running PVCs Used Bytes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"}))",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Usage Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Hourly Volume Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"}[1h])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Daily Volume Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"}[1d])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Weekly Volume Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{job=\"kubelet\", metrics_path=\"/metrics\", cluster=\"$cluster\", namespace=~\"$namespace\"}[1w])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  }
 ]
}