{ ... }:

{
  nix.settings.trusted-users = ["ryan"];

  users.groups = {
    ryan = { };
    docker = { };
    wireshark = { };
  };
  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.ryan = {
    # the hashed password with salt is generated by run `mkpasswd`.
    hashedPassword = "$y$j9T$YQu5vhlnogjDFDWp9QkPh0$Eu85OiwllqvLg5fzRVMLVHNO7InA3ro8grTJJIepyH1";
    home = "/home/ryan";
    isNormalUser = true;
    description = "ryan";
    extraGroups = [ 
      "ryan" 
      "users"
      "networkmanager" 
      "wheel"
      "docker"
      "wireshark"
      "adbusers"
      "libvirtd"
    ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDiipi59EnVbi6bK1bGrcbfEM263wgdNfbrt6VBC1rHx ryan@ai-idols"
    ];
  };
}
