{ lib, stdenvNoCC, fetchzip }:

stdenvNoCC.mkDerivation rec {
  pname = "icomoon-feather-font";
  version = "2023-05-06";

  # 参考 https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttf-icomoon-feather
  src = fetchzip {
    url = "https://github.com/adi1090x/polybar-themes/archive/47b66337a92a1afd2240ed7094ffcb039cc686cf.zip";
    # sha256 generated by ` nix-prefetch-url --unpack http://...`
    sha256 = "1dw7k0ds3z6nkqxi09pjgxl45xcfi2y0khrawxl96hcnawy3qbg8";
  };

  installPhase = ''
    runHook preInstall

    install -Dm644 fonts/feather.ttf -t $out/share/fonts/truetype/

    runHook postInstall
  '';

  meta = with lib; {
    homepage = "https://github.com/feathericons/feather";
    description = "Icomoon feather font";
    version = version;
    longDescription = ''
      Feather is a collection of simply beautiful open source icons. 
      Each icon is designed on a 24x24 grid with an emphasis on simplicity, consistency, and flexibility.
    '';
    license = licenses.mit;
    maintainers = [ maintainers.ryan4yin ];
    platforms = platforms.all;
  };
}